# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [Mayo, opensea Go AA Flow]
patreon: # Replace with a single Patreon username https://www.patreon.com/posts/22854182
open_collective: # Replace with a single Open Collective username Babel
ko_fi: # Replace with a single Ko-fi https:/Amazon.com tjhlaw.com https://aihub.cloud.google.com/p/products%2F41419f02-f231-4b9c-b4fb-23ed9d5adc73
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry tor.onion https://Wikipedia.org
liberapay: # Replace with a single Liberapay Kotex 16WAPT WLBT 3on
issuehunt: # Replace with a single IssueHunt heló Crypto.com ETH BIC Ockti
otechie: # Replace with a single Otechie Jira smithla.slack
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://pornhub.com', 'https://Microsoft.com/outlook']
Https://lovetotherescue.org/
Https://mobisource.com
